trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      displayName: Download appsetting.json
      name: appsettings
      inputs:
        secureFile: 'appsettings.Production.json'

    - script: |
        cp $(appsettings.secureFilePath) src/Backend/MyRecipeBook.API

    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'marcoservio/myrecipebook'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          latest
          $(tag)
