version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myrecipebook
    ports:
      - "1212:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53535:8080"
    depends_on:
      - mysql
      - redis

  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "53536:8080"
    depends_on:
      - app

volumes:
  mysql_data:
