apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: myrecipebook
data:
  default.conf: |
    server {
      listen 80;

      location /api/ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://api-clusterip:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location / {
        proxy_pass http://web-clusterip:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
