apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
  namespace: myrecipebook
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
